In [2]:
#Import Libraries 
import pandas as pd
import numpy as np

In [4]:
my_df = pd.DataFrame({"A" : [1,2,4,np.nan,5,np.nan,7],
                      "B" : [4,np.nan,7,np.nan,1,np.nan,2]})

# Finding Missing values with Pandas

In [5]:
my_df.isna()
my_df.isna().sum()

A    2
B    3
dtype: int64

# Dropping Missing Values with Pandas

In [7]:
my_df.dropna()
my_df.dropna(how="any") # any of the value is missing will drop it
my_df.dropna(how="all") # if all of the value in a row is missing

     A    B
0  1.0  4.0
1  2.0  NaN
2  4.0  7.0
4  5.0  1.0
6  7.0  2.0

In [9]:
my_df.dropna(how="any",subset=["A"])

     A    B
0  1.0  4.0
1  2.0  NaN
2  4.0  7.0
4  5.0  1.0
6  7.0  2.0

In [10]:
my_df.dropna(how="any",inplace= True) # To populate full data we use inplace

# Filling Missing Values with Pandas

In [11]:
my_df = pd.DataFrame({"A" : [1,2,4,np.nan,5,np.nan,7],
                      "B" : [4,np.nan,7,np.nan,1,np.nan,2]})

In [13]:
my_df.fillna(value=10000)

         A        B
0      1.0      4.0
1      2.0  10000.0
2      4.0      7.0
3  10000.0  10000.0
4      5.0      1.0
5  10000.0  10000.0
6      7.0      2.0

In [14]:
mean_value = my_df["A"].mean()

In [15]:
my_df["A"].fillna(value=mean_value)

0    1.0
1    2.0
2    4.0
3    3.8
4    5.0
5    3.8
6    7.0
Name: A, dtype: float64

In [16]:
my_df.fillna(value=my_df.mean(),inplace=True)

In [17]:
my_df

     A    B
0  1.0  4.0
1  2.0  3.5
2  4.0  7.0
3  3.8  3.5
4  5.0  1.0
5  3.8  3.5
6  7.0  2.0